import type {
  JobQueueMetric,
  PlatformAuditRecord,
  PlatformCompany,
  PlatformCompanyProvisioningInput,
  PlatformCompanySecurityPolicy,
  PlatformDashboardSummary,
  PlatformErrorRecord,
  PlatformIncidentInput,
  PlatformInvoice,
  PlatformProvisioningResult,
  PlatformRegistrationApprovalResult,
  PlatformRegistrationRequest,
  PlatformSettings,
  ProviderMonitor,
  SubscriptionPlan,
  SubscriptionPlanInput,
  SupportTicket,
  SupportTicketInput,
  SystemHealthService,
} from "@/types";
import { apiRequest } from "./apiClient";

export const superAdminApi = {
  getDashboard: () => apiRequest<PlatformDashboardSummary>("/super-admin/dashboard"),
  getCompanies: () => apiRequest<PlatformCompany[]>("/super-admin/companies"),
  getCompany: (companyId: string) => apiRequest<PlatformCompany>(`/super-admin/companies/${companyId}`),
  getCompanySecurity: (companyId: string) => apiRequest<PlatformCompanySecurityPolicy>(`/super-admin/companies/${companyId}/security`),
  saveCompanySecurity: (companyId: string, policy: PlatformCompanySecurityPolicy) => apiRequest<PlatformCompanySecurityPolicy>(`/super-admin/companies/${companyId}/security`, { method: "PUT", body: JSON.stringify(policy) }),
  createCompany: (input: PlatformCompanyProvisioningInput) => apiRequest<PlatformProvisioningResult>("/super-admin/company-onboarding", { method: "POST", body: JSON.stringify(input) }),
  getRegistrationRequests: () => apiRequest<PlatformRegistrationRequest[]>("/super-admin/registration-requests"),
  approveRegistrationRequest: (requestId: string) => apiRequest<PlatformRegistrationApprovalResult>(`/super-admin/registration-requests/${requestId}/approve`, { method: "POST" }),
  setCompanyStatus: (companyId: string, status: "active" | "suspended") => apiRequest<PlatformCompany>(`/super-admin/companies/${companyId}/status`, { method: "PATCH", body: JSON.stringify({ status }) }),
  getProviders: () => apiRequest<ProviderMonitor[]>("/super-admin/integrations"),
  getSystemHealth: () => apiRequest<SystemHealthService[]>("/super-admin/system-health"),
  getJobQueues: () => apiRequest<JobQueueMetric[]>("/super-admin/job-queues"),
  retryFailedQueueJobs: (queueId: string) => apiRequest<JobQueueMetric>(`/super-admin/job-queues/${queueId}/retry`, { method: "POST" }),
  setNonCriticalQueuesPaused: (paused: boolean) => apiRequest<{ paused: boolean; queues: JobQueueMetric[] }>("/super-admin/job-queues/pause-non-critical", { method: "POST", body: JSON.stringify({ paused }) }),
  getErrors: () => apiRequest<PlatformErrorRecord[]>("/super-admin/error-center"),
  investigateError: (errorId: string, owner: string, notes: string) => apiRequest<PlatformErrorRecord>(`/super-admin/error-center/${errorId}/investigate`, { method: "POST", body: JSON.stringify({ owner, notes }) }),
  createIncident: (input: PlatformIncidentInput) => apiRequest<PlatformErrorRecord>("/super-admin/error-center/incidents", { method: "POST", body: JSON.stringify(input) }),
  getSubscriptions: () => apiRequest<SubscriptionPlan[]>("/super-admin/subscriptions"),
  createSubscriptionPlan: (input: SubscriptionPlanInput) => apiRequest<SubscriptionPlan>("/super-admin/subscriptions", { method: "POST", body: JSON.stringify(input) }),
  updateSubscriptionPlan: (planId: string, input: SubscriptionPlanInput) => apiRequest<SubscriptionPlan>(`/super-admin/subscriptions/${planId}`, { method: "PUT", body: JSON.stringify(input) }),
  getInvoices: () => apiRequest<PlatformInvoice[]>("/super-admin/billing"),
  getInvoice: (invoiceId: string) => apiRequest<PlatformInvoice>(`/super-admin/billing/${invoiceId}`),
  getAuditLogs: () => apiRequest<PlatformAuditRecord[]>("/super-admin/audit-logs"),
  getSignedAuditExport: () => apiRequest<{ generatedAt: string; algorithm: string; signature: string; records: PlatformAuditRecord[] }>("/super-admin/audit-logs/export"),
  getSupportTickets: () => apiRequest<SupportTicket[]>("/super-admin/support"),
  createSupportTicket: (input: SupportTicketInput) => apiRequest<SupportTicket>("/super-admin/support", { method: "POST", body: JSON.stringify(input) }),
  updateSupportTicket: (ticketId: string, update: { status: SupportTicket["status"]; owner?: string }) => apiRequest<SupportTicket>(`/super-admin/support/${ticketId}`, { method: "PATCH", body: JSON.stringify(update) }),
  getSettings: () => apiRequest<PlatformSettings>("/super-admin/settings"),
  saveSettings: (settings: PlatformSettings) => apiRequest<PlatformSettings>("/super-admin/settings", { method: "PUT", body: JSON.stringify(settings) }),
  testProvider: (providerCode: string) => apiRequest<{ providerCode: string; status: string; checkedAt: string }>(`/super-admin/integrations/${providerCode}/test`, { method: "POST" }),
};
