export const permissions = {
  platformManage: "platform:manage",
  companiesManage: "companies:manage",
  platformDashboardRead: "platform:dashboard:read",
  platformCompaniesManage: "platform:companies:manage",
  platformBillingManage: "platform:billing:manage",
  platformUsageRead: "platform:usage:read",
  platformIntegrationsMonitor: "platform:integrations:monitor",
  platformHealthRead: "platform:health:read",
  platformQueuesManage: "platform:queues:manage",
  platformErrorsManage: "platform:errors:manage",
  platformAuditRead: "platform:audit:read",
  platformSupportManage: "platform:support:manage",
  platformSettingsManage: "platform:settings:manage",
  platformTenantView: "platform:tenant:view",
  dashboardRead: "dashboard:read",
  onboardingManage: "onboarding:manage",
  usersManage: "users:manage",
  ingestionManage: "ingestion:manage",
  filesRead: "files:read",
  filesUpload: "files:upload",
  filesProcess: "files:process",
  filesManage: "files:manage",
  entriesRead: "entries:read",
  entriesManage: "entries:manage",

  reviewRead: "review:read",
  reviewEdit: "review:edit",
  reviewAssign: "review:assign",
  reviewApprove: "review:approve",
  reviewRequestChanges: "review:request_changes",
  reviewSecondApprove: "review:second_approve",
  reviewExport: "review:export",

  postingRead: "posting:read",
  postingExecute: "posting:execute",
  postingRetry: "posting:retry",
  postingDownload: "posting:download",
  integrationsRead: "integrations:read",
  integrationsManage: "integrations:manage",
  integrationsTest: "integrations:test",
  integrationsSync: "integrations:sync",
  auditRead: "audit:read",
  analyticsRead: "analytics:read",
  settingsManage: "settings:manage",
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];

export const companyAdminPermissions: Permission[] = [
  permissions.dashboardRead,
  permissions.onboardingManage,
  permissions.usersManage,
  permissions.ingestionManage,
  permissions.filesRead,
  permissions.filesUpload,
  permissions.filesProcess,
  permissions.filesManage,

  permissions.entriesRead,
  permissions.entriesManage,
  permissions.reviewRead,
  permissions.reviewEdit,
  permissions.reviewAssign,
  permissions.reviewApprove,
  permissions.reviewRequestChanges,
  permissions.reviewSecondApprove,
  permissions.reviewExport,
  permissions.postingRead,
  permissions.postingExecute,
  permissions.postingRetry,
  permissions.postingDownload,
  permissions.integrationsRead,
  permissions.integrationsManage,
  permissions.integrationsTest,
  permissions.integrationsSync,
  permissions.auditRead,
  permissions.analyticsRead,
  permissions.settingsManage,
];

export const rolePermissions: Record<string, Permission[]> = {
  spectra_super_admin: Object.values(permissions),
  company_owner: companyAdminPermissions,
  company_admin: companyAdminPermissions,
  finance_manager: [
    permissions.dashboardRead,
    permissions.ingestionManage,
    permissions.filesRead,
    permissions.filesUpload,
    permissions.filesProcess,
    permissions.filesManage,
  
    permissions.entriesRead,
    permissions.entriesManage,
    permissions.reviewRead,
    permissions.reviewEdit,
    permissions.reviewAssign,
    permissions.reviewApprove,
    permissions.reviewRequestChanges,
    permissions.reviewSecondApprove,
    permissions.reviewExport,
    permissions.analyticsRead,
    permissions.auditRead,
    permissions.postingRead,
    permissions.postingDownload,
  ],
  finance_user: [
    permissions.dashboardRead,
    permissions.ingestionManage,
    permissions.filesRead,
    permissions.filesUpload,
    permissions.filesProcess,
  
    permissions.entriesRead,
    permissions.entriesManage,
    permissions.reviewRead,
  ],
  reviewer: [
    permissions.dashboardRead,
    permissions.filesRead,
    permissions.filesProcess,
  
    permissions.entriesRead,
    permissions.entriesManage,
    permissions.reviewRead,
    permissions.reviewEdit,
    permissions.reviewRequestChanges,
    permissions.reviewExport,
  ],
  approver: [
    permissions.dashboardRead,
    permissions.filesRead,
    permissions.entriesRead,
    permissions.reviewRead,
    permissions.reviewEdit,
    permissions.reviewApprove,
    permissions.reviewRequestChanges,
    permissions.reviewSecondApprove,
    permissions.reviewExport,
    permissions.auditRead,
  ],
  sap_poster: [
    permissions.dashboardRead,
    permissions.filesRead,
    permissions.reviewRead,
    permissions.postingRead,
    permissions.postingExecute,
    permissions.postingRetry,
    permissions.postingDownload,
    permissions.integrationsRead,
    permissions.integrationsTest,
    permissions.auditRead,
  ],
  integration_manager: [
    permissions.dashboardRead,
    permissions.integrationsRead,
    permissions.integrationsManage,
    permissions.integrationsTest,
    permissions.integrationsSync,
    permissions.postingRead,
    permissions.postingDownload,
    permissions.ingestionManage,
    permissions.settingsManage,
    permissions.auditRead,
  ],
  auditor: [
    permissions.dashboardRead,
    permissions.entriesRead,
    permissions.reviewRead,
    permissions.reviewExport,
    permissions.auditRead,
    permissions.analyticsRead,
    permissions.filesRead,
    permissions.postingRead,
    permissions.postingDownload,
  ],
  read_only: [
    permissions.dashboardRead,
    permissions.filesRead,
    permissions.entriesRead,
    permissions.reviewRead,
    permissions.postingRead,
    permissions.integrationsRead,
    permissions.analyticsRead,
    permissions.auditRead,
  ],
};

export const roleLabels: Record<string, string> = {
  spectra_super_admin: "SPECTRA AI Super Admin",
  company_owner: "Company Owner",
  company_admin: "Company Admin",
  finance_manager: "Finance Manager",
  finance_user: "Finance User",
  reviewer: "Reviewer",
  approver: "Approver",
  sap_poster: "SAP Poster",
  integration_manager: "Integration Manager",
  auditor: "Auditor",
  read_only: "Read-only User",
};
