"""add_ocr_tables

Revision ID: e0ee21fd6b03
Revises: cb54936db842
Create Date: 2026-06-16 07:15:55.940709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = 'e0ee21fd6b03'
down_revision = 'cb54936db842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('PADDLEOCR', 'AZURE_DI', 'AWS_TEXTRACT', 'GOOGLE_VISION', name='ocrprovider'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ocrstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('average_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_time_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['ingested_files.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_ocr_results_status'), 'ocr_results', ['status'], unique=False)
    op.create_index(op.f('ix_ocr_results_tenant_id'), 'ocr_results', ['tenant_id'], unique=False)
    op.create_table('ocr_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocr_result_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('text_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_pages_ocr_result_id'), 'ocr_pages', ['ocr_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_pages_ocr_result_id'), table_name='ocr_pages')
    op.drop_table('ocr_pages')
    op.drop_index(op.f('ix_ocr_results_tenant_id'), table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_status'), table_name='ocr_results')
    op.drop_table('ocr_results')
    # ### end Alembic commands ###
