"""Add company_onboarding table

Revision ID: f282795e5855
Revises: 14af59745484
Create Date: 2026-06-15 19:46:50.556691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'f282795e5855'
down_revision = '14af59745484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_onboarding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_profile_completed', sa.Boolean(), nullable=False),
    sa.Column('finance_config_completed', sa.Boolean(), nullable=False),
    sa.Column('users_invited', sa.Boolean(), nullable=False),
    sa.Column('integration_selected', sa.Boolean(), nullable=False),
    sa.Column('security_settings_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('selected_accounting_software', sa.String(length=50), nullable=True),
    sa.Column('selected_storage_sources', sa.JSON(), nullable=True),
    sa.Column('company_profile_completed_at', sa.DateTime(), nullable=True),
    sa.Column('finance_config_completed_at', sa.DateTime(), nullable=True),
    sa.Column('users_invited_at', sa.DateTime(), nullable=True),
    sa.Column('integration_selected_at', sa.DateTime(), nullable=True),
    sa.Column('security_settings_completed_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_onboarding_company_id'), 'company_onboarding', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_onboarding_company_id'), table_name='company_onboarding')
    op.drop_table('company_onboarding')
    # ### end Alembic commands ###
