"""Add file ingestion tables

Revision ID: cb54936db842
Revises: f282795e5855
Create Date: 2026-06-15 22:37:20.389568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'cb54936db842'
down_revision = 'f282795e5855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_link_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('GOOGLE_DRIVE', 'ONEDRIVE', 'SHAREPOINT', 'DROPBOX', 'SFTP', 'AWS_S3', 'AZURE_BLOB', 'MANUAL_URL', 'LOCAL_UPLOAD', name='ingestionsource'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_link_sources_company_id'), 'shared_link_sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_shared_link_sources_tenant_id'), 'shared_link_sources', ['tenant_id'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='batchstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['shared_link_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_company_id'), 'ingestion_batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_status'), 'ingestion_batches', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_tenant_id'), 'ingestion_batches', ['tenant_id'], unique=False)
    op.create_table('ingested_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VALIDATED', 'EXTRACTING', 'EXTRACTED', 'TRANSLATING', 'TRANSLATED', 'CLASSIFYING', 'CLASSIFIED', 'READY_FOR_REVIEW', 'COMPLETED', 'FAILED', name='filestatus'), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('virus_scanned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_files_batch_id'), 'ingested_files', ['batch_id'], unique=False)
    op.create_index(op.f('ix_ingested_files_checksum'), 'ingested_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_ingested_files_status'), 'ingested_files', ['status'], unique=False)
    op.create_index(op.f('ix_ingested_files_tenant_id'), 'ingested_files', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_files_tenant_id'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_status'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_checksum'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_batch_id'), table_name='ingested_files')
    op.drop_table('ingested_files')
    op.drop_index(op.f('ix_ingestion_batches_tenant_id'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_status'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_company_id'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index(op.f('ix_shared_link_sources_tenant_id'), table_name='shared_link_sources')
    op.drop_index(op.f('ix_shared_link_sources_company_id'), table_name='shared_link_sources')
    op.drop_table('shared_link_sources')
    # ### end Alembic commands ###
